### ISSUE TITLE
Much like Node.js module

### ISSUE THREAD

**Issue by polkovnikov-ph** [jwerle/fs.c#25]
It's not even asynchronous!

**Comment by mattn** [comment]
I'm not author, so I don't know the opinion from author. But this is minimal spec for filesystem APIs. If you want to use asynchronous APIs, you've better to use libuv.

**Comment by polkovnikov-ph** [comment]
Could we at least fix misleading readme file before closing this ticket?

**Comment by jwerle** [comment]
@polkovnikov-ph What are you looking for as an update?

> File system API much like Node's fs module (synchronous)

?

**Comment by polkovnikov-ph** [comment]
> File system API much like Node's fs module (synchronous)

Should be fine.
