### ISSUE TITLE
[WIP] Cross-platform

### ISSUE THREAD

**Issue by nagayev** [jwerle/fs.c#26]
I think this library should be cross-platform, not only for Linux.
On Windows you couldn't use `stat` function in `fs_stat`.

**Comment by jwerle** [comment]
We'd happily accept a PR! Unfortunately, I don't have time

**Comment by nagayev** [comment]
@jwerle Okey, I'll send PR. Please don't review it, I'll happy if I archive YOLO badge.

**Comment by nagayev** [comment]
@jwerle See my PR #27
